services:
  projetoprogramar:
    container_name: projeto-programar-compose
    build: .
    ports:
      - 8110:8110
    volumes:
      - ./database:/root/Prodocencia-Django/database
    networks:
      - projeto-programar-compose-network
    restart: always

networks:
  projeto-programar-compose-network:
    driver: bridge
