# Generated by Django 4.1.7 on 2023-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_counter', '0002_formqrcodecounter_landingqrcodecounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
