# Generated by Django 4.1.7 on 2023-09-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
